"""Generate compiled C++ for the H-family connection (paper: 'pre-generated code for the connection matrix').

The connection contracted with the path tangent is A_t = sum_q c_q a_q, c_q = d/dt log l_q.  On the
union sparsity pattern (43410 entries) every entry is a fixed linear combination of the 14 c_q with
rational coefficients; those coefficients are hard-coded here as exact double pairs (hi, lo), so that
the same source is exact in double (hi) and in double-double (hi + lo).

Output (gen/):
  hgen.hpp            : sizes, letter ids, declarations
  fill_<k>.cpp        : A[p] = sum_q K_pq c_q              (chunks of the pattern)
  mv_<k>.cpp          : out[i] = sum_j A[p(i,j)] in[j]     (chunks of rows), fully unrolled
Each .cpp is compiled once per precision (REAL=double / dd_real).
"""
import os, sys
from fractions import Fraction
sys.path.insert(0, '..')
from common import load_atilde_exact, ACTIVE

INP = '../../ccpipe/inputs'
OUT = 'gen'
NFILL, NMV = 48, 12
os.makedirs(OUT, exist_ok=True)

A = load_atilde_exact(os.path.join(INP, 'atilde.m'))
n = 371
letters = list(ACTIVE)
# union pattern, row-major
entries = {}
for q, k in enumerate(letters):
    for (i, j), (re, im) in A[k].items():
        if re or im:
            entries.setdefault((i, j), []).append((q, re, im))
keys = sorted(entries)
pos = {ij: p for p, ij in enumerate(keys)}
print('pattern nnz', len(keys), 'terms', sum(len(v) for v in entries.values()))


def hl(q):
    hi = float(q)
    lo = float(q - Fraction(hi))
    return hi, lo


def term(q, coef, imag):
    """C++ for coef * c[q] (coef rational, times i if imag)."""
    hi, lo = hl(coef)
    c = 'c[%d]' % q
    if imag:
        return 'MI(%s, %r, %r)' % (c, hi, lo)
    if lo == 0.0:
        if hi == 1.0: return c
        if hi == -1.0: return '(-%s)' % c
        return 'MR(%s, %r)' % (c, hi)
    return 'MD(%s, %r, %r)' % (c, hi, lo)


PRE = '''// generated by gen_code.py -- do not edit
#include "hgen.hpp"
'''
# ---- fill chunks
chunks = [keys[i::NFILL] for i in range(NFILL)]
for k, ch in enumerate(chunks):
    with open('%s/fill_%d.cpp' % (OUT, k), 'w') as f:
        f.write(PRE)
        f.write('template<class R> void hgen_fill_%d(const std::complex<R>* c, std::complex<R>* A) {\n' % k)
        for ij in ch:
            ts = []
            for q, re, im in entries[ij]:
                if re: ts.append(term(q, re, False))
                if im: ts.append(term(q, im, True))
            f.write('  A[%d] = %s;\n' % (pos[ij], ' + '.join(ts)))
        f.write('}\ntemplate void hgen_fill_%d<REAL>(const std::complex<REAL>*, std::complex<REAL>*);\n' % k)
# ---- matvec chunks (rows)
rows = {}
for (i, j) in keys:
    rows.setdefault(i, []).append(j)
rchunks = [list(range(n))[i::NMV] for i in range(NMV)]
for k, ch in enumerate(rchunks):
    with open('%s/mv_%d.cpp' % (OUT, k), 'w') as f:
        f.write(PRE)
        f.write('template<class R> void hgen_mv_%d(const std::complex<R>* A, const std::complex<R>* in, std::complex<R>* out) {\n' % k)
        for i in ch:
            js = rows.get(i, [])
            if not js:
                f.write('  out[%d] = std::complex<R>(0);\n' % i); continue
            f.write('  out[%d] = %s;\n' % (i, ' + '.join('A[%d]*in[%d]' % (pos[(i, j)], j) for j in js)))
        f.write('}\ntemplate void hgen_mv_%d<REAL>(const std::complex<R>*, const std::complex<R>*, std::complex<R>*);\n'.replace('<R>', '<REAL>') % k)
# ---- header
with open('%s/hgen.hpp' % OUT, 'w') as f:
    f.write('''// generated by gen_code.py -- do not edit
#pragma once
#include <complex>
#ifdef DIFFEQS_QD
#include <qd/dd_real.h>
#endif
namespace hgen {
constexpr int N = %d, NNZ = %d, NL = %d;
constexpr int letter_id[NL] = {%s};
}
// coefficient * c  (c complex, coefficient real: exact double hi, or double-double hi + lo)
template<class R> inline std::complex<R> MR(const std::complex<R>& c, double h) { return std::complex<R>(c.real() * h, c.imag() * h); }
template<class R> inline std::complex<R> MD(const std::complex<R>& c, double h, double l);
template<> inline std::complex<double> MD(const std::complex<double>& c, double h, double) { return MR(c, h); }
// coefficient * i * c
template<class R> inline std::complex<R> MI(const std::complex<R>& c, double h, double l);
template<> inline std::complex<double> MI(const std::complex<double>& c, double h, double) { return std::complex<double>(-c.imag() * h, c.real() * h); }
#ifdef DIFFEQS_QD
template<> inline std::complex<dd_real> MD(const std::complex<dd_real>& c, double h, double l) { const dd_real K(h, l); return std::complex<dd_real>(c.real() * K, c.imag() * K); }
template<> inline std::complex<dd_real> MI(const std::complex<dd_real>& c, double h, double l) { const dd_real K(h, l); return std::complex<dd_real>(-c.imag() * K, c.real() * K); }
#endif
''' % (n, len(keys), len(letters), ', '.join(map(str, letters))))
    for k in range(NFILL):
        f.write('template<class R> void hgen_fill_%d(const std::complex<R>* c, std::complex<R>* A);\n' % k)
    for k in range(NMV):
        f.write('template<class R> void hgen_mv_%d(const std::complex<R>* A, const std::complex<R>* in, std::complex<R>* out);\n' % k)
    f.write('template<class R> inline void hgen_fill(const std::complex<R>* c, std::complex<R>* A) {\n%s}\n'
            % ''.join('  hgen_fill_%d(c, A);\n' % k for k in range(NFILL)))
    f.write('template<class R> inline void hgen_mv(const std::complex<R>* A, const std::complex<R>* in, std::complex<R>* out) {\n%s}\n'
            % ''.join('  hgen_mv_%d(A, in, out);\n' % k for k in range(NMV)))
print('wrote', NFILL, 'fill chunks,', NMV, 'matvec chunks')

# ---- letters: c_q = d/dt log l_q at (x, y) with tangent (dx, dy); odd letters with r (special function)
from letters import PLAIN


def mono(i, j):
    f = ['x'] * i + ['y'] * j
    return '*'.join(f) if f else 'one'


def poly_cpp(p):
    ts = []
    for (i, j), c in p.items():
        m = mono(i, j)
        ts.append(('%s' % m) if c == 1 else ('(-%s)' % m if c == -1 else 'R(%d)*%s' % (c, m)))
    return ' + '.join(ts)


def dpoly(p):
    dx = {(i - 1, j): c * i for (i, j), c in p.items() if i}
    dy = {(i, j - 1): c * j for (i, j), c in p.items() if j}
    return dx, dy


with open('%s/hgen_letters.hpp' % OUT, 'w') as f:
    f.write('// generated by gen_code.py -- do not edit\n#pragma once\n#include <complex>\n')
    f.write('template<class R> inline void hgen_dlogs(const std::complex<R>& x, const std::complex<R>& y,\n'
            '    const std::complex<R>& dx, const std::complex<R>& dy, const std::complex<R>& r, std::complex<R>* c) {\n')
    f.write('  using C = std::complex<R>; const C one(1), I(0, 1);\n')
    f.write('  const C z = one - x - y, dz = -dx - dy;\n')
    f.write('  const C b = x * y * z, db = dx * y * z + x * dy * z + x * y * dz;\n')
    for q, k in enumerate(letters):
        if k in (7, 8):
            a, da = ('x * z', 'dx * z + x * dz') if k == 7 else ('x * y', 'dx * y + x * dy')
            f.write('  { const C a = %s, da = %s; c[%d] = I * (R(2) * b * da - a * db) / (r * (a * a + b)); }   // l%d\n' % (a, da, q, k))
        else:
            p = PLAIN[k]; px, py = dpoly(p)
            dterm = []
            if px: dterm.append('(%s) * dx' % poly_cpp(px))
            if py: dterm.append('(%s) * dy' % poly_cpp(py))
            f.write('  c[%d] = (%s) / (%s);   // l%d\n' % (q, ' + '.join(dterm), poly_cpp(p), k))
    f.write('}\n')
print('wrote letters')

# =====================================================================================
# Variant 2 (default): the matrix COMPILED IN AS STATIC DATA (exact hi/lo doubles) + tight loops.
# The fully unrolled variant above is correct but slower (multi-MB instruction stream per call).
# =====================================================================================
T_r, T_d, T_i = [], [], []          # (pos, q, hi, lo): exact-double real / double-double real / imaginary
for ij in keys:
    p = pos[ij]
    for q, re, im in entries[ij]:
        if re:
            hi, lo = hl(re)
            (T_r if lo == 0.0 else T_d).append((p, q, hi, lo))
        if im:
            hi, lo = hl(im)
            T_i.append((p, q, hi, lo))
rowptr = [0]
cols = []
for i in range(n):
    js = rows.get(i, [])
    cols += js
    rowptr.append(len(cols))


def arr(name, typ, vals, fmt):
    out = ['const %s %s[%d] = {' % (typ, name, max(len(vals), 1))]
    line = []
    for v in vals:
        line.append(fmt(v))
        if len(line) == 16:
            out.append('  ' + ', '.join(line) + ','); line = []
    if line: out.append('  ' + ', '.join(line) + ',')
    if not vals: out.append('  0')
    out.append('};')
    return '\n'.join(out) + '\n'


with open('%s/hgen_data.cpp' % OUT, 'w') as f:
    f.write('// generated by gen_code.py -- do not edit.  H-family connection matrices, exact as (hi, lo) doubles.\n')
    f.write('#include "hgen_data.hpp"\nnamespace hgen {\n')
    for tag, T in (('r', T_r), ('d', T_d), ('i', T_i)):
        f.write(arr('%s_pos' % tag, 'int', [t[0] for t in T], str))
        f.write(arr('%s_q' % tag, 'unsigned char', [t[1] for t in T], str))
        f.write(arr('%s_hi' % tag, 'double', [t[2] for t in T], repr))
        if tag != 'r':
            f.write(arr('%s_lo' % tag, 'double', [t[3] for t in T], repr))
    f.write(arr('rowptr', 'int', rowptr, str))
    f.write(arr('col', 'int', cols, str))
    f.write('}\n')
with open('%s/hgen_data.hpp' % OUT, 'w') as f:
    f.write('''// generated by gen_code.py -- do not edit
#pragma once
#include <complex>
#ifdef DIFFEQS_QD
#include <qd/dd_real.h>
#endif
namespace hgen {
constexpr int N = %d, NNZ = %d, NL = %d, NR = %d, ND = %d, NI = %d;
constexpr int letter_id[NL] = {%s};
extern const int r_pos[], d_pos[], i_pos[], rowptr[], col[];
extern const unsigned char r_q[], d_q[], i_q[];
extern const double r_hi[], d_hi[], d_lo[], i_hi[], i_lo[];

template<class R> inline R K(double h, double l) { return R(h) + R(l); }
#ifdef DIFFEQS_QD
template<> inline dd_real K<dd_real>(double h, double l) { return dd_real(h, l); }
#endif
template<> inline double K<double>(double h, double) { return h; }

// A[p] = sum over terms  coefficient * c[q]
template<class R> inline void fill(const std::complex<R>* c, std::complex<R>* A) {
    using C = std::complex<R>;
    for (int p = 0; p < NNZ; ++p) A[p] = C(0);
    for (int t = 0; t < NR; ++t) { const C& v = c[r_q[t]]; const double h = r_hi[t]; A[r_pos[t]] += C(v.real() * h, v.imag() * h); }
    for (int t = 0; t < ND; ++t) { const C& v = c[d_q[t]]; const R k = K<R>(d_hi[t], d_lo[t]); A[d_pos[t]] += C(v.real() * k, v.imag() * k); }
    for (int t = 0; t < NI; ++t) { const C& v = c[i_q[t]]; const R k = K<R>(i_hi[t], i_lo[t]); A[i_pos[t]] += C(-v.imag() * k, v.real() * k); }
}
// out = A in
template<class R> inline void mv(const std::complex<R>* A, const std::complex<R>* in, std::complex<R>* out) {
    using C = std::complex<R>;
    for (int i = 0; i < N; ++i) {
        R re(0), im(0);
        for (int p = rowptr[i]; p < rowptr[i + 1]; ++p) {
            const C& a = A[p]; const C& b = in[col[p]];
            re += a.real() * b.real() - a.imag() * b.imag();
            im += a.real() * b.imag() + a.imag() * b.real();
        }
        out[i] = C(re, im);
    }
}
}
''' % (n, len(keys), len(letters), len(T_r), len(T_d), len(T_i), ', '.join(map(str, letters))))
print('data variant: real-exact %d, dd %d, imaginary %d terms' % (len(T_r), len(T_d), len(T_i)))
